version: '3.1'

services:
  shorten:
    image: stefanvdlugt/shorten:latest
    build: .
    restart: unless-stopped
    env_file: settings.env
    ports:
      - "5000:5000"
    volumes:
      - ./data:/config

