"""Add ShortenedURL table

Revision ID: d945035ff4c9
Revises: 3b8bcc0eb288
Create Date: 2022-04-28 16:15:31.576672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd945035ff4c9'
down_revision = '3b8bcc0eb288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortenedURL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=True),
    sa.Column('dest', sa.String(length=2000), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortenedURL_slug'), 'shortenedURL', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortenedURL_slug'), table_name='shortenedURL')
    op.drop_table('shortenedURL')
    # ### end Alembic commands ###
